name: Release

on:
  push:
    tags: "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml -P assembly
      - name: Import GPG key
        run: |
          openssl enc -d -aes-256-cbc -K ${{ secrets.ENCRYPTION_KEY }} -iv ${{ secrets.ENCRYPTION_IV }} -in .github/workflows/secring.asc.enc -out .github/workflows/secring.asc
          gpg --import .github/workflows/secring.asc
      - name: Copy Maven Settings
        run: |
          mkdir -p ~/.m2
          cp .github/workflows/settings.xml ~/.m2/settings.xml
      - name: Release to Maven Central
        if: success()
        run: mvn -B clean deploy --file pom.xml -P assembly -DskipTests -Dsonatype.username=${{ secrets.SONATYPE_USERNAME }} -Dsonatype.password=${{ secrets.SONATYPE_PASSWORD }}
      - name: Release Plugin Archive
        uses: softprops/action-gh-release@v1
        with:
          files: target/singlestore-debezium-connector-*-plugin.tar.gz
